//
//  PromptExamples.swift
//  Fizzy
//
//  Created by Brandon Gibbons on 8/15/25.
//

import Foundation

var likedExamples = [
    "Girls drink as many sips as there are handsome guys in the room",
    "The show off bodybuilders drink 3 times",
    "Drink 2 times if you think your partner has a weird shaped sex organ",
    "Drink 1 sip if you’re single, 2 if you’re in a relationship, 3 if it’s a bit more complicated",
    "Give out 2 sips if you have been in a relationship for more than a year",
    "Select the grumpiest person among the players, he or she must drink 2 times",
    "Everyone take as many sips as the amount of years you studied after high school",
    "The girl with the biggest boobs can give out 2 sips",
    "Rock Paper Scissors challenge between the oldest and the youngest player; loser will drink 2 times",
    "Brainiacs who skipped a year in school, drink 5 times",
    "If you’re reading this sentence, drink 2 times",
    "If you were drunk yesterday, drink 2 times!",
    "The first one to come up with an inspirational saying (worthy of a cheesy poster) give out 3 sips!",
    "Hands up! Last person with their hands in the air drinks 2 times",
    "The current DJ for the evening hands out 2 sips",
    "The person with the most instagram friends, drink 3 times",
    "If you can touch your nose with your tongue, give out 2 sips",
    "If you are busy smoking right now, drink 2 times!",
    "The first person to text a family member right now can give out 2 sips!",
    "Drink 3 times if you’ve ever tried to escape a police check",
    "Those who didn’t want to play this game, drink 5 times. Such a shame",
    "Name your tinder boy, this one will drink as many times as there are girls with their last name “Tinder” in his contacts",
    "Drink 2 sips if you have ever squeezed a spot in a fitting room",
    "Drink 2 sips if you’ve ever looked for your keys in your apartment, and ended up finding them in the toilet or bathroom",
    "The person who have a blowjob most recently give out 2 sips",
    "The first to burp gives out 2 sips",
    "The next player who has to drink will triple his/her number of drinks",
    "Guys, last one to take his shirt off drinks 3 times!",
    "Drink 2 times if you’ve ever had sex in front of your pet",
    "The lovely person hosting the game of Fizzy you’re currently playing gives out 3 sips",
    "Bald people and girls with short hair, let’s take revenge! Choose someone to down their drink",
    "Redheads, let’s take revenge! Choose someone to down their drink",
    "Drink 2 times if you’ve never donated blood (bastard)",
    "Guys, drink as many sips as there are hot girls in the room",
    "The next player who has to drink gives out 3 sips",
    "The first one to show their balls, give out 4 sips",
    "Those who weight less than 125lb, get fatter by chugging your drink. Choose a player to toast with you 2 sips",
    "Guys who do the helicopter with their baton right here right now, don’t have to drink 4 sips",
    "Girls who lost a condom in their cherry drink 4 times",
    "The next player who has to drink will quadruple his/her number of drinks",
    "Drink 2 times if you’ve ever been unemployed",
    "If you ever cancelled a date because you masturbated and you did not fancy it anymore, drink 3 sips",
    "Give out 2 sips if you have at least one whitehead uglying up your face",
    "Everyone trade their pack of cigarettes",
    "At the start of each rule until the end game, the first person to audibly fart gives out 10 sips",
    "Those who didn’t want to play this drink 5 times. Such a shame",
    "If you can’t touch your toes standing up straight, drink 4 times",
    "Hi poor folks! Those who have coins in their pocket can give out one sip to those who don’t have any",
    "Name the chicken of the night, he/she has to drink 3 times",
    "Whoever removes 2 items of clothing the fastest can give out 3 sips",
    "From now on, it is forbidden to light a cigarette! Down your drink if you want to be above the law",
    "If you’re single, give 5 sips to one person",
    "5 sips to the last person to have opened a beer",
    "Drink 2 times if your socks are white",
    "Elect the one that usually goes to sleep before everyone on a night out, this person will have 2 sips",
    "Drink 2 times if you’ve slept with someone for the wrong reasons",
    "Lava monster! The last person to still have their feel on the ground drinks 3 times",
    "*name, give out 3 sips to the person you think is the most clever in the room",
    "Drink 2 times if you’ve ever made love in your parents’ bed",
    "The first player out of *name and *name2 to touch the fridge hands out 3 sips.",
    "Those who prefer a trimmed beard over a wild one, drink 2 sips",
    "*name, give one weakness for each player and drink once for each!",
    "Drink 3 sips if you don’t have Fizzy on your phone",
    "*name, do a handstand or drink 5 times",
    "Those who drank for the previous rule, drink 4 times",
    "Drink 4 times if you had erotic dreams this week",
    "The player who dated the worst girl ever, drinks 2 times",
    "*name, give out as many sips as partners you’ve dumped",
    "*name, say *name2’s birthday or drink 3 times",
    "*name, like the first 15 posts you find on instagram, or drink 3 times",
    "The first player to post a Snapchat story, give out 4 sips",
    "If you’ve scored with a MILF or a DILF, drink 2 times",
    "*name, you can give out as many sips as good qualities *name has",
    "One by one, refill your glasses, *name you start",
    "Drink 4 sips if you’ve ever mistakenly turned the flash on while trying to discretely take a picture",
    "*name, truth, dare, or drink? *name2 come up with a question or a dare",
    "*name, make up your mind: which player do you think is more rude, *name2 or *name3? This person must drink 3 sips",
    "*name, give out as many sips as there are E’s in your first name, and drink as many as there are A’s",
    "*name, make up your mind: who do you think is more comfortable around children, *name2 or *name3? This person must drink 2 sips",
    "*name and *name2 trade places, glasses as well",
    "*name, make up your mind: who do you think would have more trouble solving a math problem, *name2 or *name3? This person must drink 3 sips",
    "*name, run around the room like a pig with its throat cut or drink 4 times",
    "The top 3 silliest players drink 4 times",
    "Guys who are studying to or currently work in a fitting job drink 2 times",
    "The first person to touch *name’s feet gives out 2 sips",
    "Assholes who have asked “can I have a bite?” When someone takes out a sandwich, you drink 3 times",
    "The first person to lick their elbow gives out 100 sips",
    "*name, choose who will drink 3 times from your glass",
    "*name, name as many famous physicists as you can and hand out that many sips. You can stop whenever you want, but you will lose and have to drink 3 sips if you make a mistake",
    "*name, search for the word \"suck\" in your phone and read out the most recent text. If it's funny give out five sips, if not, drink them.",
    "*name, name the first three people you have slept with (if there are 3) and take sips for the ones you regret.",
    "*name, tell the room your favourite sex story and take a shot.",
    "Play never have I ever ( 3 fingers) oldest person starts and first person out take 5 sips.",
    "*name, have you ever slept with someone in a relationship? If so, shame on you and take 3 drinks.",
    "Who in the group has the biggest difference in age with a sexual partner. They must drink double the age difference.",
    "*name, choose someone and both of you take a shot.",
    "*name, make a rule.",
    "*name, close your eyes and let the group draw something on you. They have 3 minutes. If you refuse, finish your drink.",
    "Everyone who has made out with someone in the room. Hand out three sips if you have and drink three if you haven't.",
    "Everyone pass your shirt down 2 people to the left. Anyone who refuses, drink a sip for each person who complied.",
    "The three most broke players have to take 3 penalties",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "Everyone choose the player with the most complicated love life. They have to take 2 penalties",
    "Going around the group, play rock-paper-scissors with the person to your left. Winners give out 2 penalties.",

    "Pick the player with the messiest hair; they drink 4 sips or fix it while everyone watches",
    "The shortest player stands on a chair for the next 10 minutes. Thats it.",
    "The player with the brightest outfit hands out 3 sips to someone in dull clothes",
    "Thumb war between *name and *name2; loser drinks 2 times and compliments the winner",
    "If you can recite the alphabet backwards without pausing, give out 5 sips",
    "The first person to name 5 capital cities starting with 'B' gives out 4 sips",
    "Girls, drink as many sips as the number of exes you still follow on social media",
    "*name, do 10 push-ups or drink 3 times for each one you skip",
    "The player who traveled the farthest to be here tonight gives out 3 sips",
    "Everyone pass your phone to the right; the receiver reads one text aloud or drinks 2 times",
    "Drink 2 times if you've ever eaten food off the floor after the 5-second rule expired",
    "The most flexible player demonstrates a yoga pose; others vote if it's good or they drink 3 times",
    "If you can juggle three items right now, give out 4 sips; fail and drink them instead",
    "*name, tell a joke; if no one laughs, drink 3 times",
    "The first to solve this riddle gives out 3 sips: 'What has keys but can't open locks?' (a piano)",
    "Drink 4 times if you've ever had a wardrobe malfunction in public",
    "*name and *name2, arm wrestle; winner gives out 2 sips to the group",
    "Everyone who speaks more than one language drinks 2 sips per extra language",
    "The player with the fullest glass downs it or nominates someone else to",
    
    "Everyone must cheer the host and take a sip",
    "No pointing allowed for the next 5 minutes; drink 2 sips each time you do",
    "*name, create a silly hat from nearby items and wear it until your next turn, or drink 3 times",
    "The funniest player in the room gives out 4 sips to whoever they choose",
    "Single players drink 2 sips; couples give out 2 sips",
    "Talk like a pirate for the next round; break character and drink 3 sips",
    "Everyone wearing blue takes 2 sips",
    "*name, attempt a cartwheel; succeed and give out 3 sips, fail and drink them",
    "Keep your hands raised above your head until the next prompt, drop them and drink 2 sips",
    "Everyone pours a little of their drink into a cup; the youngest player chugs it",
    "*name, let the player to your left draw on your arm with a marker, or drink 4 times",
    "The group recreates a famous painting pose; the worst actor drinks 3 sips",
    "*name, give a genuine compliment to every player, or drink 1 sip per player",
    "No saying the word 'drink'; slip up and take 2 sips",
    "Pretend to undo an invisible seatbelt every time you stand up, forget and drink 2 times",
    "No using first names; use nicknames only, mess up and drink 2 sips",
    "If you sing along to any music, remove one item of clothing or drink 3 times",
    "*name, speak like you're on a secret service radio for the next turn",
    "Countdown from 3 like taking a photo; last to pose drinks 2 sips",
    "No laughing or smiling for the next 10 minutes; break and drink 3 times",
    "Compliment *name every time you take a sip",
    "Pump your arms like a train when you laugh; forget and drink 2 sips",
    "Every sentence starts with 'Yo' and ends with 'Check It'; mess up and drink 3 times",
    "Hold your drink with a reverse grip; switch hands and drink 2 sips",
    "No one can look directly at *name; eye contact means drink 2 sips",
    "Drink with both hands at all times; use one and take an extra sip",
    "End every sentence by moaning softly; awkward? Drink 3 times instead",
    "Take 2 sips every time someone goes to the bathroom",
    "Make every statement sound like a question?; forget and drink 2 sips?",
    "Pretend to screw your drink into the table like a lightbulb when setting it down",
    "Include a swear word in every sentence; clean mouth drinks 2 sips",
    "Next time one person drinks, everyone drinks 1 sip",
    "No eye contact with anyone; break and drink 2 sips"
]


let categorizedExamples: [String: [String]] = [
    "challenge": [
        "If you can't touch your toes standing up straight, drink 4 times",
        "If you can juggle three items right now, give out 4 sips; fail and drink them instead",
        "If you can recite the alphabet backwards without pausing, give out 5 sips",
        "The first to burp gives out 2 sips",
        "If you can touch your nose with your tongue, give out 2 sips",
        "The first to solve this riddle gives out 3 sips: 'What has keys but can't open locks?' (a piano)",
        "*name, attempt a cartwheel; succeed and give out 3 sips, fail and drink them"
    ],
    "voting game": [
        "The funniest player in the room gives out 4 sips to whoever they choose",
        "Pick the player with the messiest hair; they drink 4 sips or fix it while everyone watches",
        "*name, give out 3 sips to the person you think is the most clever in the room",
        "The person who have a blowjob most recently give out 2 sips",
        "Those who weight less than 125lb, get fatter by chugging your drink. Choose a player to toast with you 2 sips",
        "Select the grumpiest person among the players, he or she must drink 2 times",
        "Elect the one that usually goes to sleep before everyone on a night out, this person will have 2 sips",
        "Who in the group has the biggest difference in age with a sexual partner. They must drink double the age difference.",
        "The most flexible player demonstrates a yoga pose; others vote if it's good or they drink 3 times",
        "Everyone choose the player with the most complicated love life. They have to take 2 penalties",
        "The person with the most instagram friends, drink 3 times",
        "The top 3 silliest players drink 4 times",
        "*name, choose someone and both of you take a shot.",
        "*name, search for the word \"suck\" in your phone and read out the most recent text. If it's funny give out five sips, if not, drink them.",
        "Redheads, let's take revenge! Choose someone to down their drink",
        "*name, choose who will drink 3 times from your glass",
        "The three most broke players have to take 3 penalties",
        "Bald people and girls with short hair, let's take revenge! Choose someone to down their drink"
    ],
    "story": [
        "*name, tell the room your favourite sex story and take a shot.",
        "*name, tell a joke; if no one laughs, drink 3 times",
        "The first player to post a Snapchat story, give out 4 sips",
        "*name, name the first three people you have slept with (if there are 3) and take sips for the ones you regret."
    ],
    "targeting": [
        "*name, truth, dare, or drink? *name2 come up with a question or a dare",
        "*name and *name2, arm wrestle; winner gives out 2 sips to the group",
        "Compliment *name every time you take a sip",
        "One by one, refill your glasses, *name you start",
        "*name, congratulations. Maximum penalty for you.",
        "*name, name as many famous physicists as you can and hand out that many sips. You can stop whenever you want, but you will lose and have to drink 3 sips if you make a mistake",
        "Girls drink as many sips as there are handsome guys in the room",
        "*name, speak like you're on a secret service radio for the next turn",
        "*name, create a silly hat from nearby items and wear it until your next turn, or drink 3 times",
        "Guys, last one to take his shirt off drinks 3 times!",
        "*name, like the first 15 posts you find on instagram, or drink 3 times",
        "If you're single, give 5 sips to one person",
        "Girls who lost a condom in their cherry drink 4 times",
        "The next player who has to drink gives out 3 sips",
        "*name, make a rule.",
        "The next player who has to drink will quadruple his/her number of drinks",
        "The player who dated the worst girl ever, drinks 2 times",
        "Thumb war between *name and *name2; loser drinks 2 times and compliments the winner",
        "Hands up! Last person with their hands in the air drinks 2 times",
        "*name, make up your mind: who do you think is more comfortable around children, *name2 or *name3? This person must drink 2 sips",
        "*name, close your eyes and let the group draw something on you. They have 3 minutes. If you refuse, finish your drink.",
        "Name your tinder boy, this one will drink as many times as there are girls with their last name \"Tinder\" in his contacts",
        "*name, do 10 push-ups or drink 3 times for each one you skip",
        "*name, give a genuine compliment to every player, or drink 1 sip per player",
        "*name, give out as many sips as partners you've dumped",
        "*name, give one weakness for each player and drink once for each!",
        "*name, let the player to your left draw on your arm with a marker, or drink 4 times",
        "The player who traveled the farthest to be here tonight gives out 3 sips",
        "*name, run around the room like a pig with its throat cut or drink 4 times",
        "Guys, drink as many sips as there are hot girls in the room",
        "The next player who has to drink will triple his/her number of drinks",
        "*name and *name2 trade places, glasses as well",
        "*name, make up your mind: which player do you think is more rude, *name2 or *name3? This person must drink 3 sips",
        "*name, give out as many sips as there are E's in your first name, and drink as many as there are A's",
        "Single players drink 2 sips; couples give out 2 sips",
        "Drink 1 sip if you're single, 2 if you're in a relationship, 3 if it's a bit more complicated",
        "*name, say *name2's birthday or drink 3 times",
        "*name, have you ever slept with someone in a relationship? If so, shame on you and take 3 drinks.",
        "Guys who do the helicopter with their baton right here right now, don't have to drink 4 sips",
        "Guys who are studying to or currently work in a fitting job drink 2 times",
        "The first player out of *name and *name2 to touch the fridge hands out 3 sips.",
        "*name, do a handstand or drink 5 times",
        "The first person to touch *name's feet gives out 2 sips",
        "*name, make up your mind: who do you think would have more trouble solving a math problem, *name2 or *name3? This person must drink 3 sips",
        "*name, you can give out as many sips as good qualities *name has",
        "Girls, drink as many sips as the number of exes you still follow on social media",
        "No one can look directly at *name; eye contact means drink 2 sips"
    ],
    "trivia": [],
    "role-play": [
        "Talk like a pirate for the next round; break character and drink 3 sips",
        "Pretend to undo an invisible seatbelt every time you stand up, forget and drink 2 times",
        "Pretend to screw your drink into the table like a lightbulb when setting it down",
        "The group recreates a famous painting pose; the worst actor drinks 3 sips"
    ],
    "debate": [],
    "hypothetical": [
        "Drink 2 times if you've ever made love in your parents' bed",
        "The current DJ for the evening hands out 3 sips",
        "Drink 2 sips if you have ever squeezed a spot in a fitting room",
        "Drink 2 times if you've slept with someone for the wrong reasons",
        "Those who didn't want to play this game, drink 5 times. Such a shame",
        "If you ever cancelled a date because you masturbated and you did not fancy it anymore, drink 3 sips",
        "The first person to name 5 capital cities starting with 'B' gives out 4 sips",
        "Everyone take as many sips as the amount of years you studied after high school",
        "The player with the brightest outfit hands out 3 sips to someone in dull clothes",
        "Drink 4 times if you've ever had a wardrobe malfunction in public",
        "The lovely person hosting the game of Fizzy you're currently playing gives out 3 sips",
        "Drink 2 times if you think your partner has a weird shaped sex organ",
        "End every sentence by moaning softly; awkward? Drink 3 times instead",
        "If you're reading this sentence, drink 2 times",
        "5 sips to the last person to have opened a beer",
        "Drink with both hands at all times; use one and take an extra sip",
        "Everyone pours a little of their drink into a cup; the youngest player chugs it",
        "If you were drunk yesterday, drink 2 times!",
        "Drink 4 sips if you've ever mistakenly turned the flash on while trying to discretely take a picture",
        "Drink 4 times if you had erotic dreams this week",
        "The player with the fullest glass downs it or nominates someone else to",
        "Every sentence starts with 'Yo' and ends with 'Check It'; mess up and drink 3 times",
        "Drink 2 sips if you've ever looked for your keys in your apartment, and ended up finding them in the toilet or bathroom",
        "Drink 2 times if your socks are white",
        "From now on, it is forbidden to light a cigarette! Down your drink if you want to be above the law",
        "The show off bodybuilders drink 3 times",
        "Those who prefer a trimmed beard over a wild one, drink 2 sips",
        "Everyone wearing blue takes 2 sips",
        "Make every statement sound like a question?; forget and drink 2 sips?",
        "Drink 2 times if you've ever eaten food off the floor after the 5-second rule expired",
        "Brainiacs who skipped a year in school, drink 5 times",
        "Drink 3 sips if you don't have Fizzy on your phone",
        "Include a swear word in every sentence; clean mouth drinks 2 sips",
        "Pump your arms like a train when you laugh; forget and drink 2 sips",
        "Drink 3 times if you've ever tried to escape a police check",
        "Give out 2 sips if you have at least one whitehead uglying up your face",
        "Hold your drink with a reverse grip; switch hands and drink 2 sips",
        "Everyone must cheer the host and take a sip",
        "Lava monster! The last person to still have their feel on the ground drinks 3 times",
        "Those who didn't want to play this drink 5 times. Such a shame",
        "If you are busy smoking right now, drink 2 times!",
        "Hi poor folks! Those who have coins in their pocket can give out one sip to those who don't have any",
        "If you've scored with a MILF or a DILF, drink 2 times",
        "Everyone who has made out with someone in the room. Hand out three sips if you have and drink three if you haven't.",
        "Drink 2 times if you've never donated blood (bastard)",
        "Everyone who speaks more than one language drinks 2 sips per extra language",
        "If you sing along to any music, remove one item of clothing or drink 3 times",
        "Give out 2 sips if you have been in a relationship for more than a year",
        "Drink 2 times if you've ever been unemployed",
        "Countdown from 3 like taking a photo; last to pose drinks 2 sips",
        "Next time one person drinks, everyone drinks 1 sip",
        "Drink 2 times if you've ever had sex in front of your pet",
        "Those who drank for the previous rule, drink 4 times"
    ],
    "rule": [
        "No laughing or smiling for the next 10 minutes; break and drink 3 times",
        "The shortest player stands on a chair for the next 10 minutes. Thats it.",
        "Take 2 sips every time someone goes to the bathroom",
        "No eye contact with anyone; break and drink 2 sips",
        "Keep your hands raised above your head until the next prompt, drop them and drink 2 sips",
        "At the start of each rule until the end game, the first person to audibly fart gives out 10 sips",
        "No using first names; use nicknames only, mess up and drink 2 sips",
        "No saying the word 'drink'; slip up and take 2 sips",
        "No pointing allowed for the next 5 minutes; drink 2 sips each time you do"
    ],
    "mini-game": [
        "Rock Paper Scissors challenge between the oldest and the youngest player; loser will drink 2 times",
        "Play never have I ever ( 3 fingers) oldest person starts and first person out take 5 sips."
    ],
    "confession": [
        "Name the chicken of the night, he/she has to drink 3 times"
    ],
    "physical": [
        "The first person to lick their elbow gives out 100 sips"
    ],
    "social": [
        "Everyone pass your shirt down 2 people to the left. Anyone who refuses, drink a sip for each person who complied.",
        "Whoever removes 2 items of clothing the fastest can give out 3 sips",
        "Everyone pass your phone to the right; the receiver reads one text aloud or drinks 2 times",
        "The girl with the biggest boobs can give out 2 sips",
        "The first one to come up with an inspirational saying (worthy of a cheesy poster) give out 3 sips!",
        "The first person to text a family member right now can give out 2 sips!",
        "Everyone trade their pack of cigarettes",
        "Going around the group, play rock-paper-scissors with the person to your left. Winners give out 2 penalties.",
        "The first one to show their balls, give out 4 sips"
    ]
]
