//
//  PromptExamples.swift
//  Fizzy
//
//  Created by Brandon Gibbons on 8/15/25.
//

import Foundation

var likedExamples = [
    "Girls drink as many sips as there are handsome guys in the room",
    "The show off bodybuilders drink 3 times",
    "Drink 2 times if you think your partner has a weird shaped sex organ",
    "Drink 1 sip if you’re single, 2 if you’re in a relationship, 3 if it’s a bit more complicated",
    "Give out 2 sips if you have been in a relationship for more than a year",
    "Select the grumpiest person among the players, he or she must drink 2 times",
    "Everyone take as many sips as the amount of years you studied after high school",
    "The girl with the biggest boobs can give out 2 sips",
    "Rock Paper Scissors challenge between the oldest and the youngest player; loser will drink 2 times",
    "Brainiacs who skipped a year in school, drink 5 times",
    "If you’re reading this sentence, drink 2 times",
    "If you were drunk yesterday, drink 2 times!",
    "The first one to come up with an inspirational saying (worthy of a cheesy poster) give out 3 sips!",
    "Hands up! Last person with their hands in the air drinks 2 times",
    "The current DJ for the evening hands out 2 sips",
    "The person with the most instagram friends, drink 3 times",
    "If you can touch your nose with your tongue, give out 2 sips",
    "If you are busy smoking right now, drink 2 times!",
    "The first person to text a family member right now can give out 2 sips!",
    "Drink 3 times if you’ve ever tried to escape a police check",
    "Those who didn’t want to play this game, drink 5 times. Such a shame",
    "Name your tinder boy, this one will drink as many times as there are girls with their last name “Tinder” in his contacts",
    "Drink 2 sips if you have ever squeezed a spot in a fitting room",
    "Drink 2 sips if you’ve ever looked for your keys in your apartment, and ended up finding them in the toilet or bathroom",
    "The person who have a blowjob most recently give out 2 sips",
    "The first to burp gives out 2 sips",
    "The next player who has to drink will triple his/her number of drinks",
    "Guys, last one to take his shirt off drinks 3 times!",
    "Drink 2 times if you’ve ever had sex in front of your pet",
    "The lovely person hosting the game of Fizzy you’re currently playing gives out 3 sips",
    "Bald people and girls with short hair, let’s take revenge! Choose someone to down their drink",
    "Redheads, let’s take revenge! Choose someone to down their drink",
    "Drink 2 times if you’ve never donated blood (bastard)",
    "Guys, drink as many sips as there are hot girls in the room",
    "The next player who has to drink gives out 3 sips",
    "The first one to show their balls, give out 4 sips",
    "Those who weight less than 125lb, get fatter by chugging your drink. Choose a player to toast with you 2 sips",
    "Guys who do the helicopter with their baton right here right now, don’t have to drink 4 sips",
    "Girls who lost a condom in their cherry drink 4 times",
    "The next player who has to drink will quadruple his/her number of drinks",
    "Drink 2 times if you’ve ever been unemployed",
    "If you ever cancelled a date because you masturbated and you did not fancy it anymore, drink 3 sips",
    "Give out 2 sips if you have at least one whitehead uglying up your face",
    "Everyone trade their pack of cigarettes",
    "At the start of each rule until the end game, the first person to audibly fart gives out 10 sips",
    "Those who didn’t want to play this drink 5 times. Such a shame",
    "If you can’t touch your toes standing up straight, drink 4 times",
    "Hi poor folks! Those who have coins in their pocket can give out one sip to those who don’t have any",
    "Name the chicken of the night, he/she has to drink 3 times",
    "Whoever removes 2 items of clothing the fastest can give out 3 sips",
    "From now on, it is forbidden to light a cigarette! Down your drink if you want to be above the law",
    "If you’re single, give 5 sips to one person",
    "5 sips to the last person to have opened a beer",
    "Drink 2 times if your socks are white",
    "Elect the one that usually goes to sleep before everyone on a night out, this person will have 2 sips",
    "Drink 2 times if you’ve slept with someone for the wrong reasons",
    "Lava monster! The last person to still have their feel on the ground drinks 3 times",
    "*name, give out 3 sips to the person you think is the most clever in the room",
    "Drink 2 times if you’ve ever made love in your parents’ bed",
    "The first player out of *name and *name to touch the fridge hands out 3 sips.",
    "Those who prefer a trimmed beard over a wild one, drink 2 sips",
    "*name, give one weakness for each player and drink once for each!",
    "Drink 3 sips if you don’t have Fizzy on your phone",
    "*name, do a handstand or drink 5 times",
    "Those who drank for the previous rule, drink 4 times",
    "Drink 4 times if you had erotic dreams this week",
    "The player who dated the worst girl ever, drinks 2 times",
    "*name, give out as many sips as partners you’ve dumped",
    "*name, say *name’s birthday or drink 3 times",
    "*name, like the first 15 posts you find on instagram, or drink 3 times",
    "The first player to post a Snapchat story, give out 4 sips",
    "If you’ve scored with a MILF or a DILF, drink 2 times",
    "*name, you can give out as many sips as good qualities *name has",
    "One by one, refill your glasses, *name you start",
    "Drink 4 sips if you’ve ever mistakenly turned the flash on while trying to discretely take a picture",
    "*name, truth, dare, or drink? *name come up with a question or a dare",
    "*name, make up your mind: which player do you think is more rude, *name or *name? This person must drink 3 sips",
    "*name, give out as many sips as there are E’s in your first name, and drink as many as there are A’s",
    "*name, make up your mind: who do you think is more comfortable around children, *name or *name? This person must drink 2 sips",
    "*name and *name trade places, glasses as well",
    "*name, make up your mind: who do you think would have more trouble solving a math problem, *name or *name? This person must drink 3 sips",
    "*name, post something dumb (on a social app of your choice). The sentence must contain the words “lead”, “squid”, “Segway” and “*name”, end it with #fizzy Or down your drink",
    "*name, run around the room like a pig with its throat cut or drink 4 times",
    "The top 3 silliest players drink 4 times",
    "Guys who are studying to or currently work in a fitting job drink 2 times",
    "The first person to touch *name’s feet gives out 2 sips",
    "Assholes who have asked “can I have a bite?” When someone takes out a sandwich, you drink 3 times",
    "The first person to lick their elbow gives out 100 sips",
    "*name, choose who will drink 3 times from your glass",
    "*name, name as many famous physicists as you can and hand out that many sips. You can stop whenever you want, but you will lose and have to drink 3 sips if you make a mistake",
    "*name, search for the word \"suck\" in your phone and read out the most recent text. If it's funny give out five sips, if not, drink them.",
    "*name, name the first three people you have slept with (if there are 3) and take sips for the ones you regret.",
    "*name, tell the room your favourite sex story and take a shot.",
    "Play never have I ever ( 3 fingers) oldest person starts and first person out take 5 sips.",
    "*name, have you ever slept with someone in a relationship? If so, shame on you and take 3 drinks.",
    "Who in the group has the biggest difference in age with a sexual partner. They must drink double the age difference.",
    "*name, choose someone and both of you take a shot.",
    "*name, make a rule.",
    "*name, close your eyes and let the group draw something on you. They have 3 minutes. If you refuse, finish your drink.",
    "Everyone who has made out with someone in the room. Hand out three sips if you have and drink three if you haven't.",
    "Everyone pass your shirt down 2 people to the left. Anyone who refuses, drink a sip for each person who complied.",
    "The three most broke players have to take 3 penalties",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "*name, congratulations. Maximum penalty for you.",
    "Everyone choose the player with the most complicated love life. They have to take 2 penalties",
    "Going around the group, play rock-paper-scissors with the person to your left. Winners give out 2 penalties."
]
